# Generated by Django 5.0.6 on 2024-05-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezervacija',
            options={'managed': True},
        ),
    ]
