from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('proizvodi/', prikazProizvoda, name='proizvodi'),
    path('zaposleni/', prikazZaposlenih, name='zaposleni'),
    path('cenovnik/', cenovnik, name='cenovnik'),
    path('jedanProizvod/', jedanProizvod, name='jedanProizvod'),
    path('add_to_cart/<int:idp>/', add_to_cart, name='add_to_cart'),
    path('update_cart/<int:idp>/<str:action>/', update_cart, name='update_cart'),
    path('finalize_order/', finalize_order, name='finalize_order'),
    path('validate_discount_code/', validate_discount_code, name='validate_discount_code'),
    path('korpa/', cart_view, name='korpa'),
    path('login/', login, name='login'),
    path('musterije/', musterije, name='musterije'),
    path('nalog/', nalog, name='nalog'),
    path('nalogOcena/', nalogOcena, name='nalogOcena'),
    path('omiljeno/', omiljeno_view, name='omiljeno'),
    path('oNama/', oNama, name='oNama'),
    path('registracija/', registracija, name='registracija'),
    path('send_html_email/<int:idrez>/', send_html_email, name='send_html_email'),
    # path('proba/', proba, name='proba'),
    path('proba1/', proba1, name='proba1'),
    path('registracijaZaposleni/', registracijaZaposleni, name='registracijaZaposleni'),
    path('izmenaLozinka/', izmenaLozinka, name='izmenaLozinka'),
    path('izmenaKorime/', izmenaKorime, name='izmenaKorime'),
    path('izmenaEmail/', izmenaEmail, name='izmenaEmail'),
    path('izmenaTelefon/', izmenaTelefon, name='izmenaTelefon'),
    path('add_to_favorites/<int:idp>/', add_to_favorites, name='add_to_favorites'),
    path('remove_from_favorites/<int:idp>/', remove_from_favorites, name='remove_from_favorites'),
    path('otkazivanjeTermina/<int:idrez>/', otkazivanjeTermina, name='otkazivanjeTermina'),
    path('proveraBrisanjaTermina/<int:idrez>/', proveraBrisanjaTermina, name='proveraBrisanjaTermina'),
    path('logout/', logout, name='logout'),
    path('zaposleniRaspored', zaposleniRaspored, name='zaposleniRaspored'),
    path('musterijaRaspored', musterijaRaspored, name='musterijaRaspored'),
    path('zaboravljena_lozinka/', zaboravljena_lozinka_view, name='zaboravljena_lozinka'),
    path('zaboravljena_lozinka/pitanja/', lozinka_pitanja_view, name='lozinka_pitanja'),
    path('zaboravljena_lozinka/promena/', lozinka_promena_view, name='lozinka_promena'),
    path('zaboravljena_lozinka/potvrda/', lozinka_promena_potvrda, name='zaboravljena_lozinka_potvrda'),
    path('delete_from_cart/<int:idp>/', delete_from_cart, name='delete_from_cart'),
    path('proizvodi/jedanProizvod/<int:idp>/', jedanProizvod, name='jedanProizvod'),
    path('zaposleni/pojedinacniZaposleni/<int:idz>/', pojedinacniZaposleni, name='pojedinacniZaposleni'),
    path('prikazMogRasporeda/', prikazMogRasporeda, name='prikazMogRasporeda'),
    path('', index, name='index')
]